In [1]:
from collections import Counter
import re
import datetime
import os

import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
DATA_DIR = '../../data/'

TRAIN_OUTPUT_FILENAME = f'{DATA_DIR}clean/misconduct_train.pkl'
TEST_OUTPUT_FILENAME = f'{DATA_DIR}clean/misconduct_test.pkl'

In [3]:
def normalize_column_name(string):
    return re.sub('\s', '_', string).lower()

In [4]:
misconduct = pd.read_csv(f'{DATA_DIR}contractor_misconduct.csv')

In [5]:
# standardize column names
misconduct['Contractor_s'] = misconduct['Contractor(s)']
misconduct = misconduct.drop('Contractor(s)', axis=1)

misconduct.columns = [normalize_column_name(col) for col in misconduct.columns]

In [6]:
# restore improperly parsed values
misconduct['court_type'] = misconduct['court_type'].replace(np.nan, 'N/A')
# but clear these
misconduct['court_type'] = misconduct['court_type'].replace('Undisclosed/unknown', np.nan)
misconduct['total_penalties'] = misconduct['total_penalties'].replace(
    'Undisclosed/Unknown',
    np.nan
)
# (note: capitalization discrepency in 'unknown')

In [7]:
# casting
misconduct.loc[:, 'total_penalties'] = misconduct.loc[:, 'total_penalties'].astype(float)
misconduct.loc[:, 'date'] = pd.to_datetime(
    misconduct.loc[:, 'date'],
    format='%m/%d/%Y'
)

In [8]:
misconduct_train, misconduct_test = train_test_split(
    misconduct,
    test_size=0.2,
    random_state=83
)

In [9]:
os.system(f'touch {TRAIN_OUTPUT_FILENAME}')
with open(TRAIN_OUTPUT_FILENAME, 'wb') as train_file:
    pickle.dump(misconduct_train, train_file)

os.system(f'touch {TEST_OUTPUT_FILENAME}')
with open(TEST_OUTPUT_FILENAME, 'wb') as test_file:
    pickle.dump(misconduct_test, test_file)

In [50]:
misconduct_train[
    (misconduct_train.disposition_type != 'Pending') &
    (~ misconduct_train.disposition_type.isnull()) &
    (misconduct_train.contracting_party != 'None')
].sort_values('date', ascending=False)[:19]

instance  \
1576  Contracting Suspension - Anham FZCO and Anham USA   
1094         Contracting Suspension - Abul Huda Farouki   
2327  Rigging Bids on Department of Defense Fuel Sup...   
2217  Rigging Bids on Department of Defense Fuel Sup...   
1881  Air Force Battlefield Communications Contracts...   
1176  Audit of Justice Management Division MEGA 4 Co...   
728   Vandenberg Air Force Base Superfund Cleanup Costs   
1696                       NSA Contract Labor Mischarge   
1657  Alleged Hanford Site Small Business Subcontrac...   
183   Hunters Point Naval Shipyard Cleanup - Crimina...   
1891  Hanford WTP Worker Health and Safety Violation...   
371                         Redstone Arsenal Back Wages   
2353     Alleged Eurofighter Fraud - German Prosecution   
1016     Labor Violations at Alexandria, VA Call Center   
2310                       Overcharges on Army Contract   
1072  Sexual Harassment and Retaliation at Florence,...   
2426               Subcontractor Whistleblower Reprisal   
1639  Evolved Expendable Launch Vehicle Program Qual...   
799       Counterfeit Helicopter Engine Microprocessors   

                            date_type       date            misconduct_type  \
1576               Date of Suspension 2018-12-27  Government Contract Fraud   
1094               Date of Suspension 2018-12-17  Government Contract Fraud   
2327  Date of Settlement Announcement 2018-11-14  Government Contract Fraud   
2217        Date of Plea Announcement 2018-11-14  Government Contract Fraud   
1881  Date of Settlement Announcement 2018-11-02  Government Contract Fraud   
1176                   Date of Report 2018-10-31       Cost/Labor Mischarge   
728            Date of Consent Decree 2018-07-30                Environment   
1696  Date of Settlement Announcement 2018-07-06       Cost/Labor Mischarge   
1657  Date of Settlement Announcement 2018-06-07  Government Contract Fraud   
183   Date of Sentencing Announcement 2018-05-03  Government Contract Fraud   
1891                     Date of PNOV 2018-04-25                      Labor   
371   Date of Resolution Announcement 2018-03-12                      Labor   
2353        Date of Fine Announcement 2018-02-09                     Ethics   
1016                Date of Complaint 2018-01-30                      Labor   
2310  Date of Settlement Announcement 2018-01-17  Government Contract Fraud   
1072  Date of Settlement Announcement 2018-01-08                      Labor   
2426                   Date of Report 2018-01-03                      Labor   
1639                Date of IG Report 2017-12-20  Poor Contract Performance   
799   Date of Settlement Announcement 2017-12-19  Government Contract Fraud   

              disposition_type      court_type   enforcement_agency  \
1576   Suspend/Debar - Company  Administrative    Defense - General   
1094  Suspend/Debar - Employee  Administrative    Defense - General   
2327                Settlement           Civil              Justice   
2217            Pleaded Guilty        Criminal    Multiple Agencies   
1881                Settlement           Civil    Multiple Agencies   
1176     Investigative Finding             N/A              Justice   
728                 Settlement           Civil  Defense - Air Force   
1696                Settlement           Civil              Justice   
1657                Settlement           Civil              Justice   
183             Pleaded Guilty        Criminal              Justice   
1891               Restitution  Administrative               Energy   
371                Restitution             N/A                Labor   
2353                      Fine  Administrative        International   
1016                Settlement  Administrative                 NLRB   
2310                Settlement           Civil              Justice   
1072                Settlement           Civil    Multiple Agencies   
2426     Investigative Finding             N/A    Defense - General   
1639   

In [58]:
misconduct_train.loc[
    [
        740,
        854,
        1569,
        1616,
#         1639,
        2217
    ],
    [
        'instance',
        'contractor_s',
        'contracting_party',
        'misconduct_type',
        'enforcement_agency',
        'court_type',
        'disposition_type',
        'total_penalties'
    ]
].iloc[4, 0]

'Rigging Bids on Department of Defense Fuel Supply Contracts - Criminal Prosecution'

In [59]:
plt.hist(misconduct_train.disposition_type)

([array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0.